name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello abhishek welcome to DEVOPS World!"
      - name: Print goodbye
        run: echo "KEEP practicing like Mathss ! Programmig is same - bye!"
